
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ANNEGILLIAN
 */
public class RADIOBTN1 extends javax.swing.JFrame {

    /**
     * Creates new form RADIOBTN1
     */
    public RADIOBTN1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        Rselectanimal = new javax.swing.JLabel();
        Rbird = new javax.swing.JRadioButton();
        Rcat = new javax.swing.JRadioButton();
        Rdog = new javax.swing.JRadioButton();
        Rrabbit = new javax.swing.JRadioButton();
        Rpig = new javax.swing.JRadioButton();
        Rpicdisplay = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Rselectanimal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Rselectanimal.setText("SELECT ANIMAL");

        buttonGroup1.add(Rbird);
        Rbird.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Rbird.setText("BIRD");
        Rbird.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbirdActionPerformed(evt);
            }
        });

        buttonGroup1.add(Rcat);
        Rcat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Rcat.setText("CAT");
        Rcat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RcatActionPerformed(evt);
            }
        });

        buttonGroup1.add(Rdog);
        Rdog.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Rdog.setText("DOG");
        Rdog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RdogActionPerformed(evt);
            }
        });

        buttonGroup1.add(Rrabbit);
        Rrabbit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Rrabbit.setText("RABBIT");
        Rrabbit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RrabbitActionPerformed(evt);
            }
        });

        buttonGroup1.add(Rpig);
        Rpig.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Rpig.setText("PIG");
        Rpig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RpigActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Rselectanimal, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Rpig)
                    .addComponent(Rrabbit)
                    .addComponent(Rdog)
                    .addComponent(Rcat)
                    .addComponent(Rbird))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addComponent(Rpicdisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(Rselectanimal, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(Rbird)
                        .addGap(49, 49, 49)
                        .addComponent(Rcat)
                        .addGap(53, 53, 53)
                        .addComponent(Rdog)
                        .addGap(47, 47, 47)
                        .addComponent(Rrabbit)
                        .addGap(58, 58, 58)
                        .addComponent(Rpig))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(Rpicdisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RbirdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbirdActionPerformed
            ImageIcon icon= new ImageIcon(getClass().getResource("/images/bird1.jpg"));
       Rpicdisplay.setIcon(icon);
    }//GEN-LAST:event_RbirdActionPerformed

    private void RcatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RcatActionPerformed
           ImageIcon icon= new ImageIcon(getClass().getResource("/images/cat1.jpg"));
       Rpicdisplay.setIcon(icon);
    }//GEN-LAST:event_RcatActionPerformed

    private void RdogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RdogActionPerformed
           ImageIcon icon= new ImageIcon(getClass().getResource("/images/dog1.jpg"));
       Rpicdisplay.setIcon(icon);
    }//GEN-LAST:event_RdogActionPerformed

    private void RrabbitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RrabbitActionPerformed
           ImageIcon icon= new ImageIcon(getClass().getResource("/images/rabbit1.jpg"));
       Rpicdisplay.setIcon(icon);
    }//GEN-LAST:event_RrabbitActionPerformed

    private void RpigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RpigActionPerformed
           ImageIcon icon= new ImageIcon(getClass().getResource("/images/pig1.jpg"));
       Rpicdisplay.setIcon(icon);
    }//GEN-LAST:event_RpigActionPerformed
     /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RADIOBTN1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RADIOBTN1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RADIOBTN1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RADIOBTN1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RADIOBTN1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Rbird;
    private javax.swing.JRadioButton Rcat;
    private javax.swing.JRadioButton Rdog;
    private javax.swing.JLabel Rpicdisplay;
    private javax.swing.JRadioButton Rpig;
    private javax.swing.JRadioButton Rrabbit;
    private javax.swing.JLabel Rselectanimal;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    // End of variables declaration//GEN-END:variables
}
